name: Docker Push

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Docker Build & Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          args: --docker
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tmprimitivo/firego
          tag_with_ref: true  
