name: Docker Hub Push

on: 
 push:
    branches: [ master ]
    tags: "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Docker Build & Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          args: --docker
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tmprimitivo/firego
          tag_with_ref: true  

  ghregistry:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: GithubPackages-Docker
      uses: Kolkies/githubpackages-docker@v1.0.4
      with:
        # Access token which is used to deploy the image to the repository.
        repo-token:  ${{ secrets.GITHUB_TOKEN }}
        # Name for the docker image
        image-name: firego
